# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               ISClub of Cixin
tagline:             '慈心高中資訊服務社'
description:         ''
url:                 ''
baseurl:             'http://iscixin.github.io/iscixinclub'
paginate:            5

# About/contact
author:
  name:              Cixin Upper School
  url:               http://cixin.schl.tw
  email:             jimmyyen55@gmail.com

# Custom vars
version:             1.0.0

